export const pulsar = `
x = 13, y = 13, rule = B3/S23
2b2o5b2o$3b2o3b2o$o2bobobobo2bo$3ob2ob2ob3o$bobobobobobo$2b3o3b3o2$2b3o3b3o$b
obobobobobo$3ob2ob2ob3o$o2bobobobo2bo$3b2o3b2o$2b2o5b2o!
`;

export const s3911 = `
#C Generated by copy.sh/life
x = 6, y = 4, rule = B3/S23
bobo$o$bo2bo$3b3o!
`;
